### PR TITLE
ENH: don't assert out when zero results returned

### PR DESCRIPTION
**Pull request by ihnorton**

### CODE REVIEW

**Comment by pieper** [comment]
👍

**Comment by hmeine** [comment]
@jcfr This very much reminds me of the Q_ASSERT in qMidasAPI::synchronousQuery, see https://github.com/Slicer/Slicer/pull/698#issuecomment-352260024
Do you agree that such an assert is a bad thing there, as well?

**Comment by ihnorton** [comment]
FWIW, I agree 😄. It's fairly easy to trigger these conditions so it should not be fatal. I made this PR because we get multiple results if search criteria is not fully-specified using revision+platform+arch (see https://github.com/ihnorton/Slicer/commit/2e2fcef061727dc602f0ff53b7da3036af91bf9a).

**Comment by jcfr** [comment]
I am all to remove the asserts 👍 , the corresponding case just need to be handled gracefully or ignored (with a warning message or such)  if it makes sens.

**Comment by hmeine** [comment]
When writing the above comment, I assumed qMidasAPI.h was a different API, but looking at this more closely now, this PR may have tackled exactly the problem @mneugeba reported!? (I asked him via private chat.)

**Pull request merged**
